In [1]:
import numpy as np
import pandas as pd
import matplotlib.pyplot as plt

In [2]:
match = pd.read_csv('matches.csv')
delivery = pd.read_csv('deliveries.csv')

In [8]:
new=delivery.merge(match, left_on='match_id',right_on='id')

In [9]:
print(delivery.shape)
print(match.shape)

(150460, 21)
(636, 18)

In [10]:
new.shape

(150460, 39)

In [26]:
new.groupby(['season', 'batsman'])['batsman_runs'].sum().reset_index() # reset_index() - convert series into Dataframe

      season            batsman  batsman_runs
0       2008           A Chopra            42
1       2008           A Kumble            13
2       2008           A Mishra            37
3       2008           A Mukund             0
4       2008            A Nehra             3
...      ...                ...           ...
1526    2017  Washington Sundar             9
1527    2017          YK Pathan           143
1528    2017          YS Chahal            13
1529    2017       Yuvraj Singh           252
1530    2017             Z Khan             4

[1531 rows x 3 columns]

In [27]:
type(new.groupby(['season', 'batsman'])['batsman_runs'].sum()) # multi-index series

pandas.Series

In [28]:
new.groupby(['season', 'batsman'])['batsman_runs'].sum().sort_values(ascending=False).reset_index().drop_duplicates(subset='season',keep='first').sort_values('season')[['season', 'batsman']]

    season       batsman
10    2008      SE Marsh
14    2009     ML Hayden
9     2010  SR Tendulkar
11    2011      CH Gayle
2     2012      CH Gayle
3     2013    MEK Hussey
6     2014    RV Uthappa
17    2015     DA Warner
0     2016       V Kohli
7     2017     DA Warner